### ISSUE TITLE
Custom Model Sword

### ISSUE THREAD

**Issue by SirCraftypants** [LoneDev6/ItemsAdder-Sharing-Repository#6]
This is the yml code for a Custom Model Sword.
```

info:
  namespace: customitems           
  anvil_repair:
    magma_sword:
      permission:
      ingredient: EMERALD
      item: customitems:magma_sword
items:
  magma_sword:
    display_name: '&aMagma Sword'
    permission:
    resource:
      material: STONE_SWORD
      generate: true
      model_path: item/weapons/magma_sword
    durability:
      max_custom_durability: 2980
    attribute_modifiers:
      mainhand:
        attackDamage: 8.0
        attackSpeed: 2.0
```

It's recommended to not use DIAMOND_SWORD to host model Weapons due to the in game ability to upgrade a DIAMOND_SWORD in to a NETHERITE SWORD. As you can see i use STONE_SWORD as the host.

**Comment by LoneDev6** [comment]
https://github.com/LoneDev6/ItemsAdder-Sharing-Repository/blob/main/items_packs/customitems/magma_sword.yml


The diamond sword upgrade bug should already have been fixed some ItemsAdder updates ago so I didn't include your note in the yml file.
I also added the missing "recipes" entry key which was missing.

Thanks for the example!
